---
title: "Historical Fire"
author: "Jacob Bukoski"
date: "6/17/2020"
output: html_document
---

Examining database that Jeremy sent

Notes:

  - Need to identify historical fires
  - Filter all plots to those in CA (STATECD == 6)
  - 


```{r}

library(RSQLite)
library(tidyverse)

filename <- "../data/TeamPotts1.db"
sqlite.driver <- dbDriver("SQLite")
db <- dbConnect(sqlite.driver, dbname = filename)

dbListTables(db)

db_COND_LB <- dbReadTable(db, "COND_LVL_LOOK_BACKS_PNW")
db_PLOT_LB <- dbReadTable(db, "PlotLevelFireDisturbPNWFromAnnualVisitLookbacks")

```

```{r}

all_dat <- db_PLOT_LB %>%
  left_join(db_COND_LB)

head(db_COND_LB)
colnames(db_COND_LB)

q1 <- db_PLOT_LB %>%
  select(STATECD, PLOT_FIADB, DSTRBYR1, ForestAtLastPostDistVisit) %>%
  filter(ForestAtLastPostDistVisit == -1) %>%
  group_by(STATECD, PLOT_FIADB) %>%
  mutate(n = n())
        
q2 <- q1 %>%
  select(STATECD, PLOT_FIADB, n) %>%
  filter(n >= 2) %>%
  group_by(STATECD) %>%
  summarise(n2 = n_distinct(PLOT_FIADB))
  


db_COND_LB %>%
  filter(STATECD == 6) %>%
  mutate(intens_chk = ifelse(INTENSITY == 1, 1, 0)) %>%
  group_by(intens_chk, Source) %>%
  summarize(n = n()) %>%
  select(intens_chk, Source, n)

# Add forest vs. non-forest plots

test <- all_dat %>%
  filter(STATECD == 6, ForestAtLastPostDistVisit == -1) %>%
  select(PLOT_FIADB, DSTRBYR1) %>%
  distinct() %>%
  group_by(PLOT_FIADB) %>%
  mutate(n = n()) %>%
  filter(n >= 2) %>%
  summarise(n2 = n_distinct(PLOT_FIADB))

length(unique(test$PLOT_FIADB))

(db_COND_LB)

CA_dat <- db_COND_LB %>%
  filter(STATECD == 6) %>%
  arrange(PLOT_FIADB, DSTRBYR1)

unique(CA_dat$Source)

hist(CA_dat, breaks = 100, xlim = c(1900, 2020))

```


