---
title: "parseFireYears.Rmd"
author: "Jacob Bukoski"
date: "6/30/2020"
output: html_document
---

#### Load libraries and datasets

```{r}

library(readxl)
library(RSQLite)
library(tidyverse)
  
filename <- "../data/TeamPotts1.db"
sqlite.driver <- dbDriver("SQLite")
db <- dbConnect(sqlite.driver, dbname = filename)

db_COND_LB <- dbReadTable(db, "COND_LVL_LOOK_BACKS_PNW")
db_PLOT_LB <- dbReadTable(db, "PlotLevelFireDisturbPNWFromAnnualVisitLookbacks")

# Combine above two tables

all_dat <- db_PLOT_LB %>%
  left_join(db_COND_LB)

# Load in the perimeter data and the FERS CA plots

perimDat <- read_excel("../data/FireOverlay2.xlsx") %>%
  arrange(plot_fiadb, FireYear) %>%
  rename(PerimFireYear = FireYear)

fersDat <- read_csv("../data/CA_FERS.csv", col_names = T, cols(PLOT_FIADB = col_double(), FIRE_YEAR = col_double()))
cntyCds <- read_csv("../data/ca_cnty_cds.csv", col_names = T, cols(CNTY_NAME = col_character(), COUNTYCD = col_double()))

dbDisconnect(db)

```

```{r}

# From Evan's code

filename2 <- "../data/PNW_PUBLIC_SQLite.db"
sqlite.driver <- dbDriver("SQLite")
db2 <- dbConnect(sqlite.driver, dbname = filename2)

pnwFIADBcond <- dbReadTable(db2, "COND")
ForTypRef <- dbReadTable(db2, "REF_FOREST_TYPE") %>% 
  rename(FORTYPCD = REF_FORTYPCD)

OWNGRPCDref <- matrix(c(11, "National Forest.", 
                        12, "National Grassland and/or Prairie.", 
                        13, "Other Forest Service Land.", 
                        21, "National Park Service.", 
                        22, "Bureau of Land Management.", 
                        23, "Fish and Wildlife Service.", 
                        24, "Departments of Defense/Energy.", 
                        25, "Other Federal.", 
                        31, "State including State public universities.", 
                        32, "Local (County, Municipality, etc.) including water authorities.", 
                        33, "Other non-federal public.", 
                        46, "Undifferentiated private and Native American."), ncol = 2, byrow = TRUE) %>% 
  as.data.frame() %>% 
  rename( "OWNCD" = "V1", "Description" = "V2") 

OWNGRPCDref$OWNCD <- as.numeric(as.character(OWNGRPCDref$OWNCD))

```

```{r}

q1 <- all_dat %>%
  filter(STATECD == 6, ForestAtLastPostDistVisit == -1) %>%
  select(STATECD, PLOT_FIADB, INVYR, DSTRBCD1, CONDID, DSTRBYR1, Source, ForestAtLastPostDistVisit) %>%
  group_by(PLOT_FIADB) %>%    # Group by additional criteria to better identify unique plots, some plots have 
  #mutate(n = n()) %>%
  mutate(n = n_distinct(DSTRBYR1)) %>%
  filter(n >= 2) %>%
  arrange(PLOT_FIADB, DSTRBYR1, INVYR)

length(unique(q1$PLOT_FIADB))

q2 <- q1 %>%
  group_by(PLOT_FIADB) %>%
  mutate(n2 = n_distinct(interaction(PLOT_FIADB, DSTRBYR1))) %>%
  filter(n2 >= 2) %>%
  select(-ForestAtLastPostDistVisit, -n)

```

```{r}

jndData <- q2 %>%
  left_join(perimDat, by = c("PLOT_FIADB" = "plot_fiadb")) %>%
  left_join(fersDat, by = "PLOT_FIADB") %>%
  left_join(select(pnwFIADBcond, "PLOT", "CONDID", "FORTYPCD", "OWNCD", "COUNTYCD"), 
            by = c("PLOT_FIADB" = "PLOT", "CONDID")) %>%
  left_join(ForTypRef, by = "FORTYPCD") %>%
  rename(fersFireYr = FIRE_YEAR) %>%
  filter(DSTRBYR1 >= 1960) %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, PerimFireYear, fersFireYr, COUNTYCD, FORTYPCD, SWHW, OWNCD) %>%
  group_by(PLOT_FIADB) %>%
  mutate(n_FIAfires = n_distinct(DSTRBYR1),
         n_perimFires = n_distinct(PerimFireYear),
         n_ferFiresYr = n_distinct(fersFireYr)) %>%
  filter(n_FIAfires >= 2) %>%
  mutate(match = DSTRBYR1 %in% PerimFireYear | DSTRBYR1 %in% fersFireYr,
         n_match = n_distinct(match)) %>%
  ungroup()

dat2process <- jndData %>%
  filter(OWNCD == 11 | is.na(OWNCD))

n_distinct(dat2process$PLOT_FIADB)

pltsThatFlippedToSingle <- c()


```

```{r}

# Plots with exact match to perimeter fire year or FERS fire year

confirmed <- dat2process %>%
  filter(match == TRUE, n_match == 1, n_FIAfires == 2) %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, OWNCD, FORTYPCD, SWHW, COUNTYCD) %>%
  mutate(df = "cnfrmd", 
         rule = "both years confirmed by fire perimeter years",
         fireYrSrc = "FIADB") %>%
  distinct()

#write_csv(confirmed, "~/Desktop/confirmed_plots.csv")

adjList <- confirmed

n_distinct(confirmed$PLOT_FIADB)

```

```{r}

prtly_cnfrmd <- dat2process %>%
  filter(n_match == 2)

length(unique(prtly_cnfrmd$PLOT_FIADB))

#---

# Rule 1, for plots with 2 FIA fires, 1 perimeter fire year, and the most recent burn
# was confirmed by the perimeter fire year, keep the plot FIA years as long as the
# distance between the fire years is greater than 5 years. (n = 65)

prtly_p1 <- prtly_cnfrmd %>%
  group_by(PLOT_FIADB) %>%
  filter(n_FIAfires == 2 & n_perimFires == 1 & 
           (max(DSTRBYR1) %in% PerimFireYear | max(DSTRBYR1) %in% fersFireYr) & 
           (!(min(DSTRBYR1) %in% PerimFireYear) | !(min(DSTRBYR1 %in% fersFireYr)))) %>%
  mutate(dstncBtwnFires1 = abs(DSTRBYR1 - PerimFireYear),
         dstncBtwnFires2 = abs(DSTRBYR1 - fersFireYr)) %>%
  ungroup() %>%
  rowwise() %>%
  mutate(dstncBtwnFires = max(dstncBtwnFires1, dstncBtwnFires2, na.rm = T)) %>%
  select(-dstncBtwnFires1, -dstncBtwnFires2) %>%
  ungroup() %>%
  group_by(PLOT_FIADB) %>%
  mutate(n_visit = as.numeric(factor(INVYR)),
         keep = match,
         keep = ifelse(match == FALSE & dstncBtwnFires > 5, TRUE, keep),
         n_keep = n_distinct(keep)) %>%
  ungroup()

prtly_list1 <- prtly_p1 %>%
  filter(keep == TRUE & n_keep == 1) %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, OWNCD, FORTYPCD, SWHW, COUNTYCD) %>%
  unique() %>%
  mutate(df = "prtly_cnfrmd",
         rule = "rule 1",
         fireYrSrc = "FIADB")

confirmed <- add_row(confirmed, prtly_list1)

# Rule 2, for plots with two inventories and two disturbance years, but the burn
# years are less than 5 years apart and the second burn year is both (a)
# unconfirmed and (b) precedes the second burn year, adjust the second burn
# year to the confirmed fire perimeter burn year.
# Will shift plots to "single burn" category.


prtly_p2 <- prtly_p1 %>%
  filter(n_keep == 2) %>%
  arrange(PLOT_FIADB, INVYR) %>%
  group_by(PLOT_FIADB) %>%
  mutate(n_records = n(),
         keep = ifelse(n_records == 2 & DSTRBYR1 == min(DSTRBYR1) & n_visit == 2, "FERS", "FIADB"),
         DSTRBYR1 = ifelse(keep == "FERS", fersFireYr, DSTRBYR1)) %>%
  group_by(PLOT_FIADB) %>%
  mutate(n_fires = n_distinct(DSTRBYR1))

prtly_list2 <- prtly_p2 %>%
  filter(n_fires == 2) %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, keep, OWNCD, FORTYPCD, SWHW, COUNTYCD) %>%
  unique() %>%
  mutate(df = "prtly_cnfrmd",
         rule = "rule 2") %>%
  rename(fireYrSrc = keep)

confirmed <- add_row(confirmed, prtly_list2)

# Move other plots to single list (NEED TO REVISIT THESE)

# pltsThatFlippedToSingle <- prtly_p2 %>%
#   filter(n_fires == 1) %>%
#   pull(PLOT_FIADB) %>%
#   unique() %>%
#   c(pltsThatFlippedToSingle)

# Rule 3, for plots that have 2 FIA fire years, 2 perimeter fire years, the more
# recent burn confirmed by a fire perimieter year, and the historical burn before
# 1980, assign the oldest perimeter burn year to the historical fire year slot.

prtly_p3 <- prtly_cnfrmd %>%
  filter(!(PLOT_FIADB %in% confirmed$PLOT_FIADB) & !(PLOT_FIADB %in% pltsThatFlippedToSingle)) %>%
  filter(n_FIAfires == 2 & n_perimFires == 2) %>%
  group_by(PLOT_FIADB) %>%
  mutate(dstnc_minFireYr = abs(min(DSTRBYR1) - min(PerimFireYear))) %>%
  filter((min(DSTRBYR1) < 1990) & (max(DSTRBYR1) == max(PerimFireYear) & (min(DSTRBYR1) != min(PerimFireYear))) ) %>%
  mutate(fireYrSrc = ifelse(match == TRUE, "FIADB", "PERIM"),
         DSTRBYR1 = ifelse(match == TRUE, DSTRBYR1, min(PerimFireYear))) %>%
  ungroup()

prtly_list3 <- prtly_p3 %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, fireYrSrc, OWNCD, FORTYPCD, SWHW, COUNTYCD) %>%
  unique() %>%
  mutate(df = "prtly_cnfrmd",
         rule = "rule 3")

confirmed <- add_row(confirmed, prtly_list3)  

# Rule 4, for plots with 2 inventory years, 2 FIA fire years, 2 Perimeter 
# Fire Years and the difference between the oldest FIA fire and oldest Perim
# Fire year <= 10 years, substitute min(PerimFireYear) for min(DSTRBYR1)

prtly_p4 <- prtly_cnfrmd %>%
  filter(!(PLOT_FIADB %in% confirmed$PLOT_FIADB) & !(PLOT_FIADB %in% pltsThatFlippedToSingle)) %>%
  group_by(PLOT_FIADB) %>%
  filter(!any(DSTRBYR1 == 9999)) %>%
  mutate(n_invyr = n_distinct(INVYR)) %>%
  filter(n_invyr == 2 & n_FIAfires == 2 & n_perimFires == 2) %>%
  mutate(dstncBtwnMinFireYrs = abs(min(DSTRBYR1) - min(PerimFireYear))) %>%
  filter(dstncBtwnMinFireYrs < 10 & any(match == FALSE & DSTRBYR1 == min(DSTRBYR1))) %>% 
  mutate(fireYrSrc = ifelse(match == FALSE, "PERIM", "FIADB"),
         DSTRBYR1 = ifelse(fireYrSrc == "PERIM", min(PerimFireYear), DSTRBYR1))

prtly_list4 <- prtly_p4 %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, fireYrSrc, OWNCD, FORTYPCD, SWHW, COUNTYCD) %>%
  unique() %>%
  mutate(df = "prtly_cnfrmd",
         rule = "rule 4")

confirmed <- add_row(confirmed, prtly_list4)

# Rule 5, fire plots with 2 FIA fires and 2 or more perimeter fire years, calculate
# the minimum distance between the FIA fires and perimeter fire year candidates and
# keep FIADB burn yr if exact match, otherwise substitute Perimeter fire year

prtly_p5 <- prtly_cnfrmd %>%
  filter(!(PLOT_FIADB %in% confirmed$PLOT_FIADB) & !(PLOT_FIADB %in% pltsThatFlippedToSingle)) %>%
  filter(n_FIAfires == 2 & n_perimFires >= 2) %>%
  group_by(PLOT_FIADB) %>%
  filter(!any(DSTRBYR1 == 9999)) %>%
  group_by(PLOT_FIADB, INVYR, CONDID, DSTRBCD1, DSTRBYR1) %>%
  mutate(diff = abs(DSTRBYR1 - PerimFireYear)) %>%
  filter(diff == min(diff)) %>%
  group_by(PLOT_FIADB) %>%
  mutate(n_perimFires = n_distinct(PerimFireYear)) %>%
  filter(!any(diff >= 10) & min(DSTRBYR1) <= 2000 & n_perimFires == 2) %>%
  mutate(fireYrSrc = ifelse(DSTRBYR1 == PerimFireYear, "FIADB", "PERIM"),
         DSTRBYR1 = ifelse(fireYrSrc == "PERIM", PerimFireYear, DSTRBYR1))

prtly_list5 <- prtly_p5 %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, fireYrSrc, OWNCD, FORTYPCD, SWHW, COUNTYCD) %>%
  unique() %>%
  mutate(df = "prtly_cnfrmd",
         rule = "rule 5")

confirmed <- add_row(confirmed, prtly_list5)

# Rule 6, For plots with two perimeter fire years, two FIA fire years
# with one FIA fire yr confirmed and one FIA fire yr as 9999, replace the
# 9999 fire year with the second perimeter fire year.

prtly_p6 <- prtly_cnfrmd %>%
  filter(!(PLOT_FIADB %in% confirmed$PLOT_FIADB) & !(PLOT_FIADB %in% pltsThatFlippedToSingle)) %>%
  group_by(PLOT_FIADB) %>%
  filter(n_perimFires == 2 & any(DSTRBYR1 == 9999)) %>%
  mutate(fireYrSrc = ifelse(DSTRBYR1 == 9999, "PERIM", "FIADB"),
         DSTRBYR1 = ifelse(fireYrSrc == "PERIM", min(PerimFireYear), DSTRBYR1))

prtly_list6 <- prtly_p6 %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, fireYrSrc, OWNCD, FORTYPCD, SWHW, COUNTYCD) %>%
  unique() %>%
  mutate(df = "prtly_cnfrmd",
         rule = "rule 6")

confirmed <- add_row(confirmed, prtly_list6)

# How to handle fires with just one burn?

singlePerim <- prtly_cnfrmd %>%
  filter(!(PLOT_FIADB %in% confirmed$PLOT_FIADB) & !(PLOT_FIADB %in% pltsThatFlippedToSingle)) %>%
  filter(n_perimFires == 1)

# Remaining with multiple fire perimeter burn years:

prtly_p7 <- prtly_cnfrmd %>%
  filter(!(PLOT_FIADB %in% confirmed$PLOT_FIADB) & !(PLOT_FIADB %in% pltsThatFlippedToSingle)) %>%
  select(PLOT_FIADB:n_ferFiresYr)

write_csv(filter(prtly_p7, SWHW == "1_Softwoods"), "../data/forAndy/01_prtly_confirmed_SW.csv")
write_csv(filter(prtly_p7, is.na(SWHW)), "../data/forAndy/03_prtly_confirmed_NA.csv")
write_csv(filter(prtly_p7, SWHW == "2_Hardwoods"), "../data/forAndy/05_prtly_confirmed_HW.csv")

```


```{r}


uncnfrmd <- dat2process %>%
  filter(match == FALSE, n_match == 1) 

length(unique(uncnfrmd$PLOT_FIADB))

# Rule 1, If plots have two fia fire years, two perimeter fire years, the
# maximum of the perimeter fire year is not greater than the maximum of the inventory
# year, and the years do not match exactly, substitute the perimeter fire years
# for the FIA fire years.

un_p1 <- uncnfrmd %>%
  filter(n_FIAfires == 2 & n_perimFires == 2) %>%
  group_by(PLOT_FIADB) %>%
  filter(max(PerimFireYear) <= max(INVYR)) %>%
  mutate(max_diff = abs(max(PerimFireYear) - max(DSTRBYR1)),
         min_diff = abs(min(PerimFireYear) - min(DSTRBYR1))) %>%
  mutate(fireYrSrc = "PERIM") %>%
  mutate(DSTRBYR1 = ifelse(DSTRBYR1 == max(DSTRBYR1), max(PerimFireYear), min(PerimFireYear)))

un_l1 <- un_p1 %>%
  select(PLOT_FIADB, INVYR, DSTRBCD1, CONDID, Source, DSTRBYR1, fireYrSrc, OWNCD, FORTYPCD, SWHW, COUNTYCD) %>%
  unique() %>%
  mutate(df = "prtly_cnfrmd",
         rule = "rule 6")

confirmed <- add_row(confirmed, un_l1)

# Remaining unconfirmed plots

un_p2 <- uncnfrmd %>%
  filter(!(PLOT_FIADB %in% confirmed$PLOT_FIADB) & !(PLOT_FIADB %in% pltsThatFlippedToSingle)) %>%
  select(PLOT_FIADB:n_ferFiresYr)
  
write_csv(filter(un_p2, SWHW == "1_Softwoods"), "../data/forAndy/02_unconfirmed_SW.csv")
write_csv(filter(un_p2, is.na(SWHW)), "../data/forAndy/04_unconfirmed_NA.csv")
write_csv(filter(un_p2, SWHW == "2_Hardwoods"), "../data/forAndy/06_unconfirmed_HW.csv")

```


### Summary statistics of the confirmed plot data

```{r}

cntyCds <- read_csv("../data/ca_cnty_cds.csv") %>%
  mutate(region = ifelse(COUNTYCD %in% c(15, 23, 93, 105, 89, 103, 45, 21, 11, 33), "klamath", 
                          ifelse(COUNTYCD %in% c(63, 91, 57, 61, 17, 5, 3, 9, 109, 51, 43, 39, 19, 27, 107, 29), "sierra", "other")))


confirmed %>%
  group_by(OWNCD, SWHW) %>%
  summarize( n = n_distinct(PLOT_FIADB)) %>%
  View

confirmed %>%
  left_join(cntyCds, by = c("COUNTYCD")) %>%
  group_by(region, OWNCD, SWHW) %>%
  summarize(n = n_distinct(PLOT_FIADB)) %>%
  arrange(SWHW, -n) %>%
  View

```


```{r}

confirmed %>%
  filter(COUNTYCD %in% c(93, 105)) %>%
  select(PLOT_FIADB, INVYR, DSTRBYR1, SWHW, COUNTYCD) %>%
  #mutate(PLOT_FIADB = as.factor(PLOT_FIADB)) %>%
  group_by(PLOT_FIADB) %>%
  mutate(diff = max(DSTRBYR1) - min(DSTRBYR1)) %>%
  distinct() %>%
  ungroup() %>%
  arrange(COUNTYCD, PLOT_FIADB, DSTRBYR1) %>%
  ggplot(.) +
  #facet_grid(COUNTYCD ~ .) +
  geom_point(aes(y = reorder(PLOT_FIADB, DSTRBYR1), x = DSTRBYR1, col = SWHW)) +
  geom_point(aes(y = reorder(PLOT_FIADB, DSTRBYR1), x = INVYR, col = SWHW), shape = "triangle", alpha = 0.5) +
  ylab("Plot code, sorted by burn year") +
  xlab("Burn year") +
  scale_x_continuous(breaks = seq(1960, 2020, by = 10)) +
  ggtitle("Plots with confirmed multiple burns - Siskiyou & Trinity counties (CA Klamath)") +
  theme_tufte()


```

```{r}

confirmed %>%
  group_by(PLOT_FIADB) %>%
  mutate(max_diff = max(INVYR) - max(DSTRBYR1)) %>%
  select(PLOT_FIADB, max_diff) %>%
  distinct() %>%
  ggplot() +
  geom_histogram(aes(x = max_diff)) +
  scale_x_continuous(breaks = seq(0, 20, by = 2)) +
  theme_bw()


```

```{r}

confirmed %>%
  filter(SWHW == "1_Softwoods") %>%
  group_by(PLOT_FIADB) %>%
  mutate(diff = max(DSTRBYR1) - min(DSTRBYR1)) %>%
  select(PLOT_FIADB, diff) %>%
  distinct() %>%
  ungroup() %>%
  select(PLOT_FIADB, diff) %>%
  ggplot() +
  geom_histogram(aes(x = diff), position = "identity" ) +
  theme_tufte()

```

