---
title: "pnw_fiadb.Rmd"
author: "Jacob Bukoski"
date: "6/15/2020"
output: html_document
---


### Analyze the PNW FIADB

```{r}

library(RSQLite)
library(tidyverse)

```

```{r}

filename <- "../data/PNW_PUBLIC_SQLite.db"
sqlite.driver <- dbDriver("SQLite")
db <- dbConnect(sqlite.driver, dbname = filename)

dbListTables(db)

pnwFIADBplts <- dbReadTable(db, "PLOT")
pnwFIADBcond <- dbReadTable(db, "COND")
pnwFIADBcond_pnw <- dbReadTable(db, "COND_PNW")    # This table has historical disturbance codes

  
```

```{r}

join_vars <- c("STATECD", "PLOT", "INVYR")

pnwFIADB_CA <- pnwFIADBplts %>%
  #filter(STATECD == 6) %>%
  left_join(pnwFIADBcond, by = join_vars) %>%     # Join COND table
  left_join(pnwFIADBcond_pnw, by = join_vars)     # Join historical disturbances

```

```{r}

histFireFull <- pnwFIADB_CA %>%
  filter(HIST_DSTRBCD1_PNWRS %in% c(30, 31, 32)) %>%
  filter(STATECD != 2)

histFireFull %>% 
  mutate(FORGRPCD = ifelse(FORTYPCD < 400, 1, 
                           ifelse(FORTYPCD > 400 & FORTYPCD < 999, 2, 999))) %>%
  select(PLOT, HIST_DSTRBCD1_PNWRS, HIST_DSTRBYR1_PNWRS, OWNGRPCD, FORGRPCD) %>%
  distinct() %>% 
  group_by(HIST_DSTRBCD1_PNWRS, OWNGRPCD, FORGRPCD) %>%
  summarise(n = n()) %>%
  select(HIST_DSTRBCD1_PNWRS, OWNGRPCD, FORGRPCD, n) %>% 
  View

histFireFull %>% 
  filter(HIST_DSTRBYR1_PNWRS > 1900) %>%
  mutate(FORGRPCD = ifelse(FORTYPCD < 400, 1, 
                           ifelse(FORTYPCD > 400 & FORTYPCD < 999, 2, 999))) %>%
  select(PLOT, HIST_DSTRBCD1_PNWRS, HIST_DSTRBYR1_PNWRS) %>%
  distinct() %>% 
  nrow


```

---

### Filtering to those plots with both historical fire disturbance as well as more recent fire disturbance


```{r}

filt <- pnwFIADB_CA %>%
  filter(DSTRBCD1 %in% c(30, 31, 32))

histFire <- filt %>%
  filter(HIST_DSTRBCD1_PNWRS %in% c(30, 31, 32))


histFire %>%
  select(PLOT, STATECD, INVYR, DSTRBCD1, DSTRBYR1,
         HIST_DSTRBCD1_PNWRS, HIST_DSTRBYR1_PNWRS, OWNGRPCD) %>%
  distinct() %>%
  arrange(HIST_DSTRBYR1_PNWRS) %>%
  View

histFire %>%
  mutate(time_btwn_fires = DSTRBYR1 - HIST_DSTRBYR1_PNWRS) %>%
  select(PLOT, time_btwn_fires) %>% 
  distinct() %>%
  View

```


### Accessing and exploring the periodic inventory database


```{r}


filename <- "../data/IDB_CD/Database_Version_ 2.0_(zipped)/Database_Version_2.0/idb_db.sql"
sqlite.driver <- dbDriver("SQLite")
db <- dbConnect(sqlite.driver, dbname = filename, synchronous = NULL)

dbListTables(db)

pnwFIADBplts <- dbReadTable(db, "PLOT")
pnwFIADBcond <- dbReadTable(db, "COND")
pnwFIADBcond_pnw <- dbReadTable(db, "COND_PNW")    # This table has historical disturbance codes


```


